BITS 64
EXTERN IRQ_timer

GLOBAL IRQ_timer_stub

%macro pushall 0
    push rax
    push rbx
    push rcx
    push rdx
    push rdi
    push rsi
    push rbp
    push r8
    push r9
    push r10
    push r11
    push r12
    push r13
    push r14
    push r15
    mov rdi, rsp
%endmacro

%macro popall 0
    pop r15
    pop r14
    pop r13
    pop r12
    pop r11
    pop r10
    pop r9
    pop r8
    pop rbp
    pop rsi
    pop rdi
    pop rdx
    pop rcx
    pop rbx
    pop rax
%endmacro

IRQ_timer_stub:
    push 0
    pushall
    call IRQ_timer
    popall
    add rsp, 8
    iretq